### ISSUE TITLE
BindingResolutionException while returning back from steam  

### ISSUE THREAD

**Issue by BibekStha** [kanalumaddela/laravel-steam-login#39]
Hi, 

I'm new to Laravel and I think this error is more Laravel's issue than this module's but since I couldn't find the solution this problem anywhere so I'm creating an issue here.

I get this error when user logs in on steam and comes back to the website.
`Illuminate \ Contracts \ Container \`
`BindingResolutionException`
`Unresolvable dependency resolving [Parameter #0 [ <required> $steamId ]] in class kanalumaddela\LaravelSteamLogin\SteamUser`

You can view the error page from Laravel [here](https://imgur.com/a/8D6j6FL). [I didn't know better way to share image :sweat_smile:]

I have followed all the steps from your documentation. I know things are working because user can go to steam login page and when I remove 'auntheticate' method from 'SteamLoginController' class it says the method is missing while returning from steam.

**Comment by kanalumaddela** [comment]
What version of laravel are you running?
I did a fresh install of 5.8 and did the most minimal setup following my docs and everything works.

This is all I had added/edited:

`routes/web.php`
```php
Route::get('login/steam', 'Auth\SteamLoginController@login')->name('login.steam');
Route::get('auth/steam', 'Auth\SteamLoginController@authenticate')->name('auth.steam');
```
`app/Http/Controllers/Auth/SteamLoginController.php`
```php
<?php

namespace App\Http\Controllers\Auth;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use kanalumaddela\LaravelSteamLogin\Http\Controllers\AbstractSteamLoginController;
use kanalumaddela\LaravelSteamLogin\SteamUser;

class SteamLoginController extends AbstractSteamLoginController
{
    /**
     * {@inheritdoc}
     */
    public function authenticated(Request $request, SteamUser $steamUser)
    {
        $steamUser->getUserInfo();
        dd($steamUser);
    }
}
```

**Comment by BibekStha** [comment]
It couldn't find `kanalumaddela\LaravelSteamLogin\Http\Controllers\AbstractSteamLoginController` class.
I tried search for the class file in the vendor folder, I couldn't find it either. So I had used `SteamLoginHandlerController` class instead. That might have started the issue.

**Comment by BibekStha** [comment]
Seems like composer is not copying all the files from this package.

I run this command to install this package:
`composer require kanalumaddela/laravel-steam-login:^2.*`

**Comment by kanalumaddela** [comment]
Composer isn't downloading the latest version for you. It downloaded `2.2.1` instead of `2.3.2`. The `SteamLoginHandlerController` exists in `2.2.1` and was replaced (and poorly deprecated) with `AbstractSteamLoginController` in `2.3.0`. Try using just `composer require kanalumaddela/laravel-steam-login`.

When manually downloading, don't download and use the master branch. It constantly changes as I refactor/improve the code. Download from the releases page if you need to download it manually.

**As a side note**: your php is the 32-bit version, that means it can't handle large integers which will cause issues relating to steamids. This means that all steamids will show as `2147483647`. You won't be able to use this library unless you're running 64-bit php (which has been standard across all hosting/dev environments).

**Comment by BibekStha** [comment]
I tried downloading it from the master branch and it worked.. I had to reinstall xampp to get 64 bit.. I don't know why.. 
Now it is working. Thanks for all your help. I will take your advice and download it from release page.

So the only problem was that composer didn't download the updated version. I guess you can fix that in the instruction. Thanks again.
